//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGBConnect.ServiceFonctionsAdmin {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceFonctionsAdmin.IFonctionsAdmin")]
    public interface IFonctionsAdmin {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFonctionsAdmin/desactiverGestionnaireDesTaches", ReplyAction="http://tempuri.org/IFonctionsAdmin/desactiverGestionnaireDesTachesResponse")]
        bool desactiverGestionnaireDesTaches(string SSID, bool desactive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFonctionsAdmin/desactiverGestionnaireDesTaches", ReplyAction="http://tempuri.org/IFonctionsAdmin/desactiverGestionnaireDesTachesResponse")]
        System.Threading.Tasks.Task<bool> desactiverGestionnaireDesTachesAsync(string SSID, bool desactive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFonctionsAdmin/desactiverChangementMotDePasse", ReplyAction="http://tempuri.org/IFonctionsAdmin/desactiverChangementMotDePasseResponse")]
        bool desactiverChangementMotDePasse(string SSID, bool desactive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFonctionsAdmin/desactiverChangementMotDePasse", ReplyAction="http://tempuri.org/IFonctionsAdmin/desactiverChangementMotDePasseResponse")]
        System.Threading.Tasks.Task<bool> desactiverChangementMotDePasseAsync(string SSID, bool desactive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFonctionsAdmin/lireProfiles", ReplyAction="http://tempuri.org/IFonctionsAdmin/lireProfilesResponse")]
        System.Collections.Generic.Dictionary<string, string> lireProfiles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFonctionsAdmin/lireProfiles", ReplyAction="http://tempuri.org/IFonctionsAdmin/lireProfilesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> lireProfilesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFonctionsAdmin/ecrireConfiguration", ReplyAction="http://tempuri.org/IFonctionsAdmin/ecrireConfigurationResponse")]
        bool ecrireConfiguration(System.Collections.Generic.Dictionary<string, string> config);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFonctionsAdmin/ecrireConfiguration", ReplyAction="http://tempuri.org/IFonctionsAdmin/ecrireConfigurationResponse")]
        System.Threading.Tasks.Task<bool> ecrireConfigurationAsync(System.Collections.Generic.Dictionary<string, string> config);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFonctionsAdmin/lireConfiguration", ReplyAction="http://tempuri.org/IFonctionsAdmin/lireConfigurationResponse")]
        System.Collections.Generic.Dictionary<string, string> lireConfiguration();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFonctionsAdmin/lireConfiguration", ReplyAction="http://tempuri.org/IFonctionsAdmin/lireConfigurationResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> lireConfigurationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFonctionsAdmin/writeLog", ReplyAction="http://tempuri.org/IFonctionsAdmin/writeLogResponse")]
        void writeLog(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFonctionsAdmin/writeLog", ReplyAction="http://tempuri.org/IFonctionsAdmin/writeLogResponse")]
        System.Threading.Tasks.Task writeLogAsync(string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFonctionsAdminChannel : LGBConnect.ServiceFonctionsAdmin.IFonctionsAdmin, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FonctionsAdminClient : System.ServiceModel.ClientBase<LGBConnect.ServiceFonctionsAdmin.IFonctionsAdmin>, LGBConnect.ServiceFonctionsAdmin.IFonctionsAdmin {
        
        public FonctionsAdminClient() {
        }
        
        public FonctionsAdminClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FonctionsAdminClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FonctionsAdminClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FonctionsAdminClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool desactiverGestionnaireDesTaches(string SSID, bool desactive) {
            return base.Channel.desactiverGestionnaireDesTaches(SSID, desactive);
        }
        
        public System.Threading.Tasks.Task<bool> desactiverGestionnaireDesTachesAsync(string SSID, bool desactive) {
            return base.Channel.desactiverGestionnaireDesTachesAsync(SSID, desactive);
        }
        
        public bool desactiverChangementMotDePasse(string SSID, bool desactive) {
            return base.Channel.desactiverChangementMotDePasse(SSID, desactive);
        }
        
        public System.Threading.Tasks.Task<bool> desactiverChangementMotDePasseAsync(string SSID, bool desactive) {
            return base.Channel.desactiverChangementMotDePasseAsync(SSID, desactive);
        }
        
        public System.Collections.Generic.Dictionary<string, string> lireProfiles() {
            return base.Channel.lireProfiles();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> lireProfilesAsync() {
            return base.Channel.lireProfilesAsync();
        }
        
        public bool ecrireConfiguration(System.Collections.Generic.Dictionary<string, string> config) {
            return base.Channel.ecrireConfiguration(config);
        }
        
        public System.Threading.Tasks.Task<bool> ecrireConfigurationAsync(System.Collections.Generic.Dictionary<string, string> config) {
            return base.Channel.ecrireConfigurationAsync(config);
        }
        
        public System.Collections.Generic.Dictionary<string, string> lireConfiguration() {
            return base.Channel.lireConfiguration();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> lireConfigurationAsync() {
            return base.Channel.lireConfigurationAsync();
        }
        
        public void writeLog(string message) {
            base.Channel.writeLog(message);
        }
        
        public System.Threading.Tasks.Task writeLogAsync(string message) {
            return base.Channel.writeLogAsync(message);
        }
    }
}
